server:
  port: 8080
greeting:
  message: "Je m'appelle Padawan"

# Profil 'Prod'
---
spring:
  config:
    activate:
      on-profile: prod
name: prod
greeting:
  message.salutation: "Monsieur de la production, Salutations."


# Profil 'Dev'
---
spring:
  config:
    activate:
      on-profile: dev
name: dev
greeting:
  message.salutation: "Bonjour jeune d√©veloppeur dynamique !"

